//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nl.fhict.IntelliCloud.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nl.fhict.IntelliCloud.Business.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor U vraag, U zult spoedig antwoord van ons ontvangen..
        /// </summary>
        internal static string DUTCH_FACEBOOK_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("DUTCH_FACEBOOK_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=\&quot;width:500px; margin:auto;\&quot;&gt;
        ///&lt;font &lt;font face=\&quot;arial\&quot;&gt;
        ///&lt;table border=\&quot;0\&quot;&gt;&lt;tr&gt;&lt;td style=\&quot;width:276px; height:118px; \&quot;&gt; 
        ///&lt;img width=\&quot;276px\&quot; height=\&quot;118px\&quot; src=&quot;http://81.204.121.229/intellicloud/mailimages/intellilogo.png&quot; alt=\&quot;intelliCloud\&quot;/&gt; &lt;/td&gt;&lt;td&gt; &lt;p style=\&quot;float: right; \&quot;&gt; IntelliCloud bv 
        ///&lt;br&gt; Rachelsmolen 1&lt;br&gt;5612MA Eindhoven&lt;br&gt;040 - 224488 &lt;/p&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/font&gt;&lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot; width=\&quot;500px\&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;br&gt;
        ///&lt;p&gt;U heeft een vraag gesteld o [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DUTCH_MAIL_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("DUTCH_MAIL_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor u vraag!.
        /// </summary>
        internal static string DUTCH_MAIL_AUTO_RESPONSE_SUBJECT {
            get {
                return ResourceManager.GetString("DUTCH_MAIL_AUTO_RESPONSE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=\&quot;width:500px; margin:auto;\&quot;&gt;
        ///&lt;font 
        ///&lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot;&gt;&lt;tr&gt;&lt;td style=\&quot;width:276px; height:118px; \&quot;&gt; &lt;img width=\&quot;276px\&quot; height=\&quot;118px\&quot; src=&quot;http://81.204.121.229/intellicloud/mailimages/intellilogo.png&quot; alt=\&quot;intelliCloud\&quot;/&gt; &lt;/td&gt;&lt;td&gt; 
        ///&lt;p style=\&quot;float: right; \&quot;&gt; IntelliCloud bv &lt;br&gt; Rachelsmolen 1&lt;br&gt;5612MA Eindhoven&lt;br&gt;040 - 224488 &lt;/p&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/font&gt;&lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot; width=\&quot;500px\&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;br&gt;
        ///&lt;p&gt;U heeft onlangs een vraa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DUTCH_MAIL_RESPONSE {
            get {
                return ResourceManager.GetString("DUTCH_MAIL_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwoord op u vraag.
        /// </summary>
        internal static string DUTCH_MAIL_RESPONSE_SUBJECT {
            get {
                return ResourceManager.GetString("DUTCH_MAIL_RESPONSE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor U vraag, U zult spoedig antwoord van ons ontvangen..
        /// </summary>
        internal static string DUTCH_TWITTER_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("DUTCH_TWITTER_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U antwoord: {0}.
        /// </summary>
        internal static string DUTCH_TWITTER_LINK_RESPONSE {
            get {
                return ResourceManager.GetString("DUTCH_TWITTER_LINK_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your question, you will recieve a answer shortly..
        /// </summary>
        internal static string ENGLISH_FACEBOOK_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("ENGLISH_FACEBOOK_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=\&quot;width:500px; margin:auto;\&quot;&gt;&lt;font &lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot;&gt;&lt;tr&gt;&lt;td style=\&quot;width:276px; height:118px; \&quot;&gt; &lt;img width=\&quot;276px\&quot; height=\&quot;118px\&quot; src=&quot;http://81.204.121.229/intellicloud/mailimages/intellilogo.png&quot;&gt; &lt;/td&gt;&lt;td&gt; &lt;p style=\&quot;float: right; \&quot;&gt; IntelliCloud bv &lt;br&gt; Rachelsmolen 1&lt;br&gt;5612MA Eindhoven&lt;br&gt;040 - 224488 &lt;/p&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/font&gt;&lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot; width=\&quot;500px\&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;br&gt;&lt;p&gt;You have asked a question on IntelliCloud. The system  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENGLISH_MAIL_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("ENGLISH_MAIL_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=\&quot;width:500px; margin:auto;\&quot;&gt;&lt;font &lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot;&gt;&lt;tr&gt;&lt;td style=\&quot;width:276px; height:118px; \&quot;&gt; 
        ///&lt;img width=\&quot;276px\&quot; height=\&quot;118px\&quot; src=&quot;http://81.204.121.229/intellicloud/mailimages/intellilogo.png&quot; alt=\&quot;intelliCloud\&quot;/&gt; &lt;/td&gt;&lt;td&gt; 
        ///&lt;p style=\&quot;float: right; \&quot;&gt; IntelliCloud bv &lt;br&gt; Rachelsmolen 1&lt;br&gt;5612MA Eindhoven&lt;br&gt;040 - 224488 &lt;/p&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/font&gt;&lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot; width=\&quot;500px\&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;br&gt;
        ///&lt;p&gt;You have recently asked a  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ENGLISH_MAIL_RESPONSE {
            get {
                return ResourceManager.GetString("ENGLISH_MAIL_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer to your question.
        /// </summary>
        internal static string ENGLISH_MAIL_RESPONSE_SUBJECT {
            get {
                return ResourceManager.GetString("ENGLISH_MAIL_RESPONSE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your question, you will recieve a answer shortly..
        /// </summary>
        internal static string ENGLISH_TWITTER_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("ENGLISH_TWITTER_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer: {0}.
        /// </summary>
        internal static string ENGLISH_TWITTER_LINK_RESPONSE {
            get {
                return ResourceManager.GetString("ENGLISH_TWITTER_LINK_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your question!.
        /// </summary>
        internal static string ENSLIGH_MAIL_AUTO_RESPONSE_SUBJECT {
            get {
                return ResourceManager.GetString("ENSLIGH_MAIL_AUTO_RESPONSE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your question, you will recieve a answer shortly..
        /// </summary>
        internal static string UNKNOWN_FACEBOOK_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("UNKNOWN_FACEBOOK_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=\&quot;width:500px; margin:auto;\&quot;&gt;&lt;font &lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot;&gt;&lt;tr&gt;&lt;td style=\&quot;width:276px; height:118px; \&quot;&gt; &lt;img width=\&quot;276px\&quot; height=\&quot;118px\&quot; src=&quot;http://81.204.121.229/intellicloud/mailimages/intellilogo.png&quot;&gt; &lt;/td&gt;&lt;td&gt; &lt;p style=\&quot;float: right; \&quot;&gt; IntelliCloud bv &lt;br&gt; Rachelsmolen 1&lt;br&gt;5612MA Eindhoven&lt;br&gt;040 - 224488 &lt;/p&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/font&gt;&lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot; width=\&quot;500px\&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;br&gt;&lt;p&gt;You have asked a question on IntelliCloud. The system  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UNKNOWN_MAIL_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("UNKNOWN_MAIL_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your question!.
        /// </summary>
        internal static string UNKNOWN_MAIL_AUTO_RESPONSE_SUBJECT {
            get {
                return ResourceManager.GetString("UNKNOWN_MAIL_AUTO_RESPONSE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div style=\&quot;width:500px; margin:auto;\&quot;&gt;&lt;font &lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot;&gt;&lt;tr&gt;&lt;td style=\&quot;width:276px; height:118px; \&quot;&gt; 
        ///&lt;img width=\&quot;276px\&quot; height=\&quot;118px\&quot; src=\&quot;http://athena.fhict.nl/users/i241221/intelliCloud.png\&quot; alt=\&quot;intelliCloud\&quot;/&gt; &lt;/td&gt;&lt;td&gt; 
        ///&lt;p style=\&quot;float: right; \&quot;&gt; IntelliCloud bv &lt;br&gt; Rachelsmolen 1&lt;br&gt;5612MA Eindhoven&lt;br&gt;040 - 224488 &lt;/p&gt;&lt;br&gt;&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;&lt;/font&gt;&lt;font face=\&quot;arial\&quot;&gt;&lt;table border=\&quot;0\&quot; width=\&quot;500px\&quot;&gt;&lt;tr&gt;&lt;td&gt;&lt;br&gt;
        ///&lt;p&gt;You have recently asked a questi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UNKNOWN_MAIL_RESPONSE {
            get {
                return ResourceManager.GetString("UNKNOWN_MAIL_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer to your question.
        /// </summary>
        internal static string UNKNOWN_MAIL_RESPONSE_SUBJECT {
            get {
                return ResourceManager.GetString("UNKNOWN_MAIL_RESPONSE_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your question, you will recieve a answer shortly..
        /// </summary>
        internal static string UNKNOWN_TWITTER_AUTO_RESPONSE {
            get {
                return ResourceManager.GetString("UNKNOWN_TWITTER_AUTO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your answer: {0}.
        /// </summary>
        internal static string UNKNOWN_TWITTER_LINK_RESPONSE {
            get {
                return ResourceManager.GetString("UNKNOWN_TWITTER_LINK_RESPONSE", resourceCulture);
            }
        }
    }
}
