//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nl.fhict.IntelliCloud.Service.IntegrationTest.WordService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WordService.IWordService")]
    public interface IWordService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/ResolveWord", ReplyAction="http://tempuri.org/IWordService/ResolveWordResponse")]
        nl.fhict.IntelliCloud.Business.WordService.Word[] ResolveWord(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWordService/ResolveWord", ReplyAction="http://tempuri.org/IWordService/ResolveWordResponse")]
        System.Threading.Tasks.Task<nl.fhict.IntelliCloud.Business.WordService.Word[]> ResolveWordAsync(string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWordServiceChannel : nl.fhict.IntelliCloud.Service.IntegrationTest.WordService.IWordService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WordServiceClient : System.ServiceModel.ClientBase<nl.fhict.IntelliCloud.Service.IntegrationTest.WordService.IWordService>, nl.fhict.IntelliCloud.Service.IntegrationTest.WordService.IWordService {
        
        public WordServiceClient() {
        }
        
        public WordServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WordServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WordServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public nl.fhict.IntelliCloud.Business.WordService.Word[] ResolveWord(string word) {
            return base.Channel.ResolveWord(word);
        }
        
        public System.Threading.Tasks.Task<nl.fhict.IntelliCloud.Business.WordService.Word[]> ResolveWordAsync(string word) {
            return base.Channel.ResolveWordAsync(word);
        }
    }
}
