//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelliMailClient.IntelliCloud {
    using System.Runtime.Serialization;
    using System;
    using System.ServiceModel.Web;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/nl.fhict.IntelliCloud.Common.DataTransfer" +
        "")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.User AnswererField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.Keyword[] KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.SourceDefinition SourceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.User Answerer {
            get {
                return this.AnswererField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswererField, value) != true)) {
                    this.AnswererField = value;
                    this.RaisePropertyChanged("Answerer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.Keyword[] Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.SourceDefinition SourceType {
            get {
                return this.SourceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceTypeField, value) != true)) {
                    this.SourceTypeField = value;
                    this.RaisePropertyChanged("SourceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/nl.fhict.IntelliCloud.Common.DataTransfer" +
        "")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InfixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.Keyword[] KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.Source[] SourcesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Infix {
            get {
                return this.InfixField;
            }
            set {
                if ((object.ReferenceEquals(this.InfixField, value) != true)) {
                    this.InfixField = value;
                    this.RaisePropertyChanged("Infix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.Keyword[] Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.Source[] Sources {
            get {
                return this.SourcesField;
            }
            set {
                if ((object.ReferenceEquals(this.SourcesField, value) != true)) {
                    this.SourcesField = value;
                    this.RaisePropertyChanged("Sources");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SourceDefinition", Namespace="http://schemas.datacontract.org/2004/07/nl.fhict.IntelliCloud.Common.DataTransfer" +
        "")]
    [System.SerializableAttribute()]
    public partial class SourceDefinition : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Keyword", Namespace="http://schemas.datacontract.org/2004/07/nl.fhict.IntelliCloud.Common.DataTransfer" +
        "")]
    [System.SerializableAttribute()]
    public partial class Keyword : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AffinityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Affinity {
            get {
                return this.AffinityField;
            }
            set {
                if ((this.AffinityField.Equals(value) != true)) {
                    this.AffinityField = value;
                    this.RaisePropertyChanged("Affinity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Source", Namespace="http://schemas.datacontract.org/2004/07/nl.fhict.IntelliCloud.Common.DataTransfer" +
        "")]
    [System.SerializableAttribute()]
    public partial class Source : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.SourceDefinition SourceDefinitionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.SourceDefinition SourceDefinition {
            get {
                return this.SourceDefinitionField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceDefinitionField, value) != true)) {
                    this.SourceDefinitionField = value;
                    this.RaisePropertyChanged("SourceDefinition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/nl.fhict.IntelliCloud.Common.DataTransfer" +
        "")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AnswerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AnswerId {
            get {
                return this.AnswerIdField;
            }
            set {
                if ((this.AnswerIdField.Equals(value) != true)) {
                    this.AnswerIdField = value;
                    this.RaisePropertyChanged("AnswerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answer", Namespace="http://schemas.datacontract.org/2004/07/nl.fhict.IntelliCloud.Common.DataTransfer" +
        "")]
    [System.SerializableAttribute()]
    public partial class Answer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.AnswerState AnswerStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.Keyword[] KeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.Question QuestionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private IntelliMailClient.IntelliCloud.User UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.AnswerState AnswerState {
            get {
                return this.AnswerStateField;
            }
            set {
                if ((this.AnswerStateField.Equals(value) != true)) {
                    this.AnswerStateField = value;
                    this.RaisePropertyChanged("AnswerState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreationTime {
            get {
                return this.CreationTimeField;
            }
            set {
                if ((this.CreationTimeField.Equals(value) != true)) {
                    this.CreationTimeField = value;
                    this.RaisePropertyChanged("CreationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.Keyword[] Keywords {
            get {
                return this.KeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.KeywordsField, value) != true)) {
                    this.KeywordsField = value;
                    this.RaisePropertyChanged("Keywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.Question Question {
            get {
                return this.QuestionField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionField, value) != true)) {
                    this.QuestionField = value;
                    this.RaisePropertyChanged("Question");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public IntelliMailClient.IntelliCloud.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnswerState", Namespace="http://schemas.datacontract.org/2004/07/nl.fhict.IntelliCloud.Common.DataTransfer" +
        "")]
    public enum AnswerState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Send = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnderReview = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Accepted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Declined = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntelliCloud.IIntelliCloudService")]
    public interface IIntelliCloudService {
        
        [WebInvokeAttribute(BodyStyle=WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/AskQuestion", ReplyAction="http://tempuri.org/IIntelliCloudService/AskQuestionResponse")]
        void AskQuestion(string source, string reference, string question);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/AskQuestion", ReplyAction="http://tempuri.org/IIntelliCloudService/AskQuestionResponse")]
        System.Threading.Tasks.Task AskQuestionAsync(string source, string reference, string question);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/SendAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/SendAnswerResponse")]
        void SendAnswer(string questionId, string answerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/SendAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/SendAnswerResponse")]
        System.Threading.Tasks.Task SendAnswerAsync(string questionId, string answerId);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/CreateAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/CreateAnswerResponse")]
        void CreateAnswer(string questionId, string answer, string answererId, string answerState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/CreateAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/CreateAnswerResponse")]
        System.Threading.Tasks.Task CreateAnswerAsync(string questionId, string answer, string answererId, string answerState);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/UpdateAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/UpdateAnswerResponse")]
        void UpdateAnswer(string answerId, string answerState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/UpdateAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/UpdateAnswerResponse")]
        System.Threading.Tasks.Task UpdateAnswerAsync(string answerId, string answerState);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetQuestions", ReplyAction="http://tempuri.org/IIntelliCloudService/GetQuestionsResponse")]
        IntelliMailClient.IntelliCloud.Question[] GetQuestions(string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetQuestions", ReplyAction="http://tempuri.org/IIntelliCloudService/GetQuestionsResponse")]
        System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Question[]> GetQuestionsAsync(string employeeId);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/AcceptAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/AcceptAnswerResponse")]
        void AcceptAnswer(string feedback, string answerId, string questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/AcceptAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/AcceptAnswerResponse")]
        System.Threading.Tasks.Task AcceptAnswerAsync(string feedback, string answerId, string questionId);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/DeclineAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/DeclineAnswerResponse")]
        void DeclineAnswer(string feedback, string answerId, string questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/DeclineAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/DeclineAnswerResponse")]
        System.Threading.Tasks.Task DeclineAnswerAsync(string feedback, string answerId, string questionId);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/SendReviewForAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/SendReviewForAnswerResponse")]
        void SendReviewForAnswer(string reviewerId, string answerId, string review);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/SendReviewForAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/SendReviewForAnswerResponse")]
        System.Threading.Tasks.Task SendReviewForAnswerAsync(string reviewerId, string answerId, string review);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/UpdateReview", ReplyAction="http://tempuri.org/IIntelliCloudService/UpdateReviewResponse")]
        void UpdateReview(string reviewId, string reviewState);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/UpdateReview", ReplyAction="http://tempuri.org/IIntelliCloudService/UpdateReviewResponse")]
        System.Threading.Tasks.Task UpdateReviewAsync(string reviewId, string reviewState);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetReviewsForAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/GetReviewsForAnswerResponse")]
        IntelliMailClient.IntelliCloud.Review[] GetReviewsForAnswer(string answerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetReviewsForAnswer", ReplyAction="http://tempuri.org/IIntelliCloudService/GetReviewsForAnswerResponse")]
        System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Review[]> GetReviewsForAnswerAsync(string answerId);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetAnswersUpForReview", ReplyAction="http://tempuri.org/IIntelliCloudService/GetAnswersUpForReviewResponse")]
        IntelliMailClient.IntelliCloud.Answer[] GetAnswersUpForReview(string employeeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetAnswersUpForReview", ReplyAction="http://tempuri.org/IIntelliCloudService/GetAnswersUpForReviewResponse")]
        System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Answer[]> GetAnswersUpForReviewAsync(string employeeId);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetAnswerById", ReplyAction="http://tempuri.org/IIntelliCloudService/GetAnswerByIdResponse")]
        IntelliMailClient.IntelliCloud.Answer GetAnswerById(string answerId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetAnswerById", ReplyAction="http://tempuri.org/IIntelliCloudService/GetAnswerByIdResponse")]
        System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Answer> GetAnswerByIdAsync(string answerId);

        [WebInvokeAttribute(BodyStyle = WebMessageBodyStyle.Wrapped)]
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetQuestionById", ReplyAction="http://tempuri.org/IIntelliCloudService/GetQuestionByIdResponse")]
        IntelliMailClient.IntelliCloud.Question GetQuestionById(string questionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelliCloudService/GetQuestionById", ReplyAction="http://tempuri.org/IIntelliCloudService/GetQuestionByIdResponse")]
        System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Question> GetQuestionByIdAsync(string questionId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntelliCloudServiceChannel : IntelliMailClient.IntelliCloud.IIntelliCloudService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntelliCloudServiceClient : System.ServiceModel.ClientBase<IntelliMailClient.IntelliCloud.IIntelliCloudService>, IntelliMailClient.IntelliCloud.IIntelliCloudService {
        
        public IntelliCloudServiceClient() {
        }
        
        public IntelliCloudServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IntelliCloudServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntelliCloudServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IntelliCloudServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AskQuestion(string source, string reference, string question) {
            base.Channel.AskQuestion(source, reference, question);
        }
        
        public System.Threading.Tasks.Task AskQuestionAsync(string source, string reference, string question) {
            return base.Channel.AskQuestionAsync(source, reference, question);
        }
        
        public void SendAnswer(string questionId, string answerId) {
            base.Channel.SendAnswer(questionId, answerId);
        }
        
        public System.Threading.Tasks.Task SendAnswerAsync(string questionId, string answerId) {
            return base.Channel.SendAnswerAsync(questionId, answerId);
        }
        
        public void CreateAnswer(string questionId, string answer, string answererId, string answerState) {
            base.Channel.CreateAnswer(questionId, answer, answererId, answerState);
        }
        
        public System.Threading.Tasks.Task CreateAnswerAsync(string questionId, string answer, string answererId, string answerState) {
            return base.Channel.CreateAnswerAsync(questionId, answer, answererId, answerState);
        }
        
        public void UpdateAnswer(string answerId, string answerState) {
            base.Channel.UpdateAnswer(answerId, answerState);
        }
        
        public System.Threading.Tasks.Task UpdateAnswerAsync(string answerId, string answerState) {
            return base.Channel.UpdateAnswerAsync(answerId, answerState);
        }
        
        public IntelliMailClient.IntelliCloud.Question[] GetQuestions(string employeeId) {
            return base.Channel.GetQuestions(employeeId);
        }
        
        public System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Question[]> GetQuestionsAsync(string employeeId) {
            return base.Channel.GetQuestionsAsync(employeeId);
        }
        
        public void AcceptAnswer(string feedback, string answerId, string questionId) {
            base.Channel.AcceptAnswer(feedback, answerId, questionId);
        }
        
        public System.Threading.Tasks.Task AcceptAnswerAsync(string feedback, string answerId, string questionId) {
            return base.Channel.AcceptAnswerAsync(feedback, answerId, questionId);
        }
        
        public void DeclineAnswer(string feedback, string answerId, string questionId) {
            base.Channel.DeclineAnswer(feedback, answerId, questionId);
        }
        
        public System.Threading.Tasks.Task DeclineAnswerAsync(string feedback, string answerId, string questionId) {
            return base.Channel.DeclineAnswerAsync(feedback, answerId, questionId);
        }
        
        public void SendReviewForAnswer(string reviewerId, string answerId, string review) {
            base.Channel.SendReviewForAnswer(reviewerId, answerId, review);
        }
        
        public System.Threading.Tasks.Task SendReviewForAnswerAsync(string reviewerId, string answerId, string review) {
            return base.Channel.SendReviewForAnswerAsync(reviewerId, answerId, review);
        }
        
        public void UpdateReview(string reviewId, string reviewState) {
            base.Channel.UpdateReview(reviewId, reviewState);
        }
        
        public System.Threading.Tasks.Task UpdateReviewAsync(string reviewId, string reviewState) {
            return base.Channel.UpdateReviewAsync(reviewId, reviewState);
        }
        
        public IntelliMailClient.IntelliCloud.Review[] GetReviewsForAnswer(string answerId) {
            return base.Channel.GetReviewsForAnswer(answerId);
        }
        
        public System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Review[]> GetReviewsForAnswerAsync(string answerId) {
            return base.Channel.GetReviewsForAnswerAsync(answerId);
        }
        
        public IntelliMailClient.IntelliCloud.Answer[] GetAnswersUpForReview(string employeeId) {
            return base.Channel.GetAnswersUpForReview(employeeId);
        }
        
        public System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Answer[]> GetAnswersUpForReviewAsync(string employeeId) {
            return base.Channel.GetAnswersUpForReviewAsync(employeeId);
        }
        
        public IntelliMailClient.IntelliCloud.Answer GetAnswerById(string answerId) {
            return base.Channel.GetAnswerById(answerId);
        }
        
        public System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Answer> GetAnswerByIdAsync(string answerId) {
            return base.Channel.GetAnswerByIdAsync(answerId);
        }
        
        public IntelliMailClient.IntelliCloud.Question GetQuestionById(string questionId) {
            return base.Channel.GetQuestionById(questionId);
        }
        
        public System.Threading.Tasks.Task<IntelliMailClient.IntelliCloud.Question> GetQuestionByIdAsync(string questionId) {
            return base.Channel.GetQuestionByIdAsync(questionId);
        }
    }
}
